trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build Frontend and Backend
  jobs:
  - job: frontend
    displayName: Build Frontend
    steps:
    - checkout: self
      clean: true

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: Install Node.js

    - script: |
        cd frontend
        npm ci
        npm run build
      displayName: Install deps & build

    - task: ArchiveFiles@2
      displayName: Archive frontend
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/frontend/build'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      displayName: Publish Frontend artifact
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/frontend.zip'
        artifactName: 'Frontend'
        publishLocation: 'Container'

  - job: backend
    displayName: Build Backend
    steps:
    - checkout: self
      clean: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'
      displayName: Set Python Version

    # Optional: only install if requirements.txt exists
    - script: |
        python -m pip install --upgrade pip
        if [ -f "$(Build.SourcesDirectory)/backend/requirements.txt" ]; then
          pip install -r "$(Build.SourcesDirectory)/backend/requirements.txt"
        else
          echo "No backend/requirements.txt found; skipping pip install."
        fi
      displayName: Install backend deps (optional)

    - task: ArchiveFiles@2
      displayName: Archive backend
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/backend'
        includeRootFolder: true
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      displayName: Publish Backend artifact
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/backend.zip'
        artifactName: 'Backend'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy Frontend and Backend
  dependsOn: Build
  jobs:
  - job: deploy
    displayName: Deploy
    steps:
    - script: echo "Deployment step goes here"
      displayName: Placeholder for Deployment
