trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: "Build Frontend and Backend"
    jobs:
      - job: frontend
        displayName: "Build Frontend"
        steps:
          - checkout: self
            clean: true

          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              echo "Installing dependencies..."
              cd frontend
              npm install
            displayName: 'Install Frontend Dependencies'

          - script: |
              echo "Building frontend..."
              cd frontend
              npm run build
            displayName: 'Build Frontend'

          - script: |
              echo "Zipping build output..."
              cd frontend/build
              zip -r ../../frontend.zip .
            displayName: 'Zip Frontend Build Output'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'frontend.zip'
              artifactName: 'Frontend'
              publishLocation: 'Container'

      - job: backend
        displayName: "Build Backend"
        steps:
          - checkout: self
            clean: true

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.11'
            displayName: 'Set Python Version'

          - script: |
              echo "Installing backend dependencies and zipping..."
              cd backend
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              zip -r ../backend.zip .
            displayName: 'Install & Zip Backend Code'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'backend.zip'
              artifactName: 'Backend'
              publishLocation: 'Container'

  - stage: Deploy
    displayName: "Deploy Frontend and Backend"
    dependsOn: Build
    jobs:
      - job: deploy
        displayName: "Deploy"
        steps:
          - script: echo "Deployment step goes here"
            displayName: 'Placeholder for Deployment'